language: node_js
sudo: false
script: "./_scripts/run-tests.sh"
branches:
  except:
  - master
node_js:
  - '6.1'
cache:
  bundler: true
  directories:
    - node_modules

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GH_USERNAME: aav7fl
  - GH_REPO: aav7fl.github.io
  - GH_SOURCE_BRANCH: source
  - GH_DEST_BRANCH: master
  - secure: ol4s+iUpSC3U0+dhIcefHohs02ehUIpOHTnsd6MNGFIkFK65rP13ytQfhwcLsZtUBx6T+gA+ECRvJc/Ild4rRYPfyjr0Ao/7khQJX6sU9rXxxmoKVgIe+Fz6e9W89atZoLVLjeHmEQSZUkzyOAl6F+25h4Q26sB7aRvoTPcnRGAMG4lDwz/SC5gXS7ENN1f+7avm2bB08TRc5ic/PQu5q01/vlyA6El2/VOWF8z+Q51eAtDeQGlkm2kQ66poK8H8olZzg+bYn/Vrjq9umQ09Ic2R+/zbChRPaoVYcRw7tp0N3EyT4hJU1WGQ6CZbNfv2+c5TMCEBe16Fit0Ad6/g9bqZhKZuGBm7GpB3DXbi8Zuv2faq/2hgQ6TAPF9VNrKpufbS0c2OtlKcjXGlueeLf6aEHuCM9sDQkxs2akW0hM000h0Plw9rjnla0q4bnNv9GjC4fH4c5ICjCBXNMhtUYcR6ij2jop3F/3VztsP6oY3E9PzqKuAR7KgP8nYe4mbk3rwGGFYUiC+2UC/MDm6FCwkXlc3RhGLBKwjDZ6dkCpp2kAb0j6nhKPJhB61i1N45PysAyqYcMI9jL+YU1gMUE27nhZgTakdgNPLagcFcbUXyrPLq7G4TR2GP0ZojwXGYRQXZU8bB8ROBR/oaucT67dtsyyE51ZnSqxTT9RmxCVo=

before_install:
  # - rvm install 2.2.6 # RVM 2.2.6 should already be availible.
  - rvm use 2.2.6

install:
  - gem install bundler
  - bundle install
  # - npm install # Handled by Travis automatically.

deploy:
  provider: script
  script: "./_scripts/deploy.sh"
  skip_cleanup: true
  on:
    branch: source

notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
